### ISSUE TITLE
Druidcrafts Dreadfish swimming in mid-air in YAMDA mining dimension

### ISSUE THREAD

**Issue by DietmarKrause** [MysticMods/Druidcraft#10]
Druidcrafts Dreadfish swimming in mid-air in YAMDA mining dimension in modpack all the mods 4.  I havent seen them elsewhere until now. This seems to be a bug.

**Comment by DietmarKrause** [comment]
https://github.com/AllTheMods/ATM-4/issues/39

**Comment by VulpTheHorseDog** [comment]
Not a bug, Dreadfish are meant to be spooky, glowy, flying fish. It's intentional.
