### ISSUE TITLE
Crash Involving Ticking Entity (Beetle)

### ISSUE THREAD

**Issue by anatevka-xD** [MysticMods/Druidcraft#101]
[crash-2021-02-21_23.09.39-server.txt](https://github.com/MysticMods/Druidcraft/files/6019464/crash-2021-02-21_23.09.39-server.txt)

Crash when joining my server. It is heavily modded so it's possible it's an issue with mod interaction, but thought it'd be worth posting here.

Description: Ticking entity

java.lang.ClassCastException: com.vulp.druidcraft.entities.BeetleEntity cannot be cast to net.minecraft.entity.player.PlayerEntity

**Comment by noobanidus** [comment]
ForestCraft appears to be attempting to cast BeetleEntity in PlayerEntity.

The error here would lie with them and I'd recommend checking out their issue tracker or CurseForge.

While it is the beetle from Druidcraft, it's another mod (Forestcraft) that's performing the class cast and thus causing the exception.
