### ISSUE TITLE
Here you have the translation of the mod into Spanish

### ISSUE THREAD

**Issue by Scrulius** [MysticMods/Druidcraft#108]
{
  "block.druidcraft.hold_shift": "Mantén pulsado [SHIFT] para más información.",
  "item.druidcraft.hold_shift": "Mantén pulsado [SHIFT] para más información.",

  "item.druidcraft.hemp": "Cáñamo",
  "item.druidcraft.hemp_seeds": "Semillas de cáñamo",
  "item.druidcraft.amber": "Ámbar",
  "item.druidcraft.moonstone": "Piedra lunar",
  "item.druidcraft.fiery_glass": "Cristal ardiente",
  "item.druidcraft.rockroot": "Raíz de piedra",
  "item.druidcraft.chitin": "Quitina",
  "item.druidcraft.soulfire": "Fuego fatuo",
  "item.druidcraft.wooden_sickle": "Hoz de madera",
  "item.druidcraft.stone_sickle": "Hoz de piedra",
  "item.druidcraft.iron_sickle": "Hoz de hierro",
  "item.druidcraft.gold_sickle": "Hoz de oro",
  "item.druidcraft.diamond_sickle": "Hoz de diamante",
  "item.druidcraft.dreadfish_spawn_egg": "Generar Pez del terror",
  "item.druidcraft.beetle_spawn_egg": "Generar escarabajo",
  "item.druidcraft.lunar_moth_spawn_egg": "Generar polilla lunar",
  "item.druidcraft.bone_sword": "Espada de hueso",
  "item.druidcraft.bone_shovel": "Pala de hueso",
  "item.druidcraft.bone_pickaxe": "Pico de hueso",
  "item.druidcraft.bone_axe": "Hacha de hueso",
  "item.druidcraft.bone_hoe": "Azada de hueso",
  "item.druidcraft.bone_sickle": "Hoz de hueso",
  "item.druidcraft.bone_helmet": "Casco de hueso",
  "item.druidcraft.bone_chestplate": "Peto de hueso",
  "item.druidcraft.bone_leggings": "Grebas de hueso",
  "item.druidcraft.bone_boots": "Botas de hueso",
  "item.druidcraft.bone_shield": "Escudo de hueso",
  "item.druidcraft.knife": "Cuchillo",
  "item.druidcraft.knife.description1": "Utilízalo para configurar bloques de cuerda.",
  "item.druidcraft.turquoise_lunar_moth_egg": "Generar polilla lunar turquesa",
  "item.druidcraft.white_lunar_moth_egg": "Generar polilla lunar blanca",
  "item.druidcraft.lime_lunar_moth_egg": "Generar polilla lunar lima",
  "item.druidcraft.yellow_lunar_moth_egg": "Generar polilla lunar amarilla",
  "item.druidcraft.orange_lunar_moth_egg": "Generar polilla lunar naranja",
  "item.druidcraft.pink_lunar_moth_egg": "Generar polilla lunar rosa",
  "item.druidcraft.blueberries": "Arándanos",
  "item.druidcraft.elderberries": "Baya del saúco",
  "item.druidcraft.elderflower": "Flor de saúco",
  "item.druidcraft.blueberry_muffin": "Muffin de arándanos",
  "item.druidcraft.apple_elderberry_crumble": "Migas de manzana y baya del saúco",
  "item.druidcraft.elderflower_cordial": "Refresco de flor de saúco",
  "item.druidcraft.moonstone_sword": "Espada de piedra lunar",
  "item.druidcraft.moonstone_shovel": "Pala de piedra lunar",
  "item.druidcraft.moonstone_pickaxe": "Pico de piedra lunar",
  "item.druidcraft.moonstone_axe": "Hacha de piedra lunar",
  "item.druidcraft.moonstone_hoe": "Azada de piedra lunar",
  "item.druidcraft.moonstone_sickle": "Hoz de piedra lunar",
  "item.druidcraft.moonstone_helmet": "Casco de piedra lunar",
  "item.druidcraft.moonstone_chestplate": "Peto de piedra lunar",
  "item.druidcraft.moonstone_leggings": "Grebas de piedra lunar",
  "item.druidcraft.moonstone_boots": "Botas de piedra lunar",
  "item.druidcraft.moonstone_shield": "Escudo de piedra lunar",
  "item.druidcraft.chitin_helmet": "Casco de quitina",
  "item.druidcraft.chitin_chestplate": "Peto de quitina",
  "item.druidcraft.chitin_leggings": "Grebas de quitina",
  "item.druidcraft.chitin_boots": "Botas de quitina",
  "item.druidcraft.chitin_shield": "Escudo de quitina",
  "item.druidcraft.travel_pack": "Mochila",
  "item.druidcraft.travel_pack.description1": "Pequeña mochila con ranuras especiales.",
  "item.druidcraft.travel_pack.button1": "Saco de dormir",
  "item.druidcraft.travel_pack.button2": "(NYI)",
  "item.druidcraft.travel_pack.button3": "(NYI)",
  "item.druidcraft.travel_pack.button4": "(NYI)",
  "item.druidcraft.crushed_fiery_glass": "Crushed Fiery Glass",
  "item.druidcraft.brightstone": "Brightstone",
  "item.druidcraft.tempered_fiery_glass": "Tempered Fiery Glass",
  "item.druidcraft.blazing_steel": "Blazing Steel",
  "item.druidcraft.heart_of_blaze": "Heart of Blaze",
  "item.druidcraft.infernal_lantern": "Infernal Lantern",
  "item.druidcraft.infernal_lantern.description1": "Flares: ",
  "item.druidcraft.infernal_lantern.description2": "A blazing lantern capable of storing many flares to light up an area.",
  "item.druidcraft.infernal_lantern.failure": "No flares left!",
  "item.druidcraft.infernal_lantern.success": "Remaining flares: ",

  "block.druidcraft.amber_ore": "Mena de ámbar",
  "block.druidcraft.moonstone_ore": "Mena de piedra lunar",
  "block.druidcraft.fiery_glass_ore": "Mena de cristal ardiente",
  "block.druidcraft.rockroot_ore": "Bloque de raíz de piedra",
  "block.druidcraft.amber_block": "Bloque de ámbar",
  "block.druidcraft.moonstone_block": "Bloque de piedra lunar",
  "block.druidcraft.fiery_glass_block": "Bloque de cristal ardiente",
  "block.druidcraft.rockroot_block": "Bloque de raíces de piedra",
  "block.druidcraft.darkwood_log": "Tronco de madera oscura",
  "block.druidcraft.stripped_darkwood_log": "Tronco de madera oscura sin corteza",
  "block.druidcraft.darkwood_leaves": "Hojas de madera oscura",
  "block.druidcraft.darkwood_sapling": "Brote de de madera oscura",
  "block.druidcraft.darkwood_planks": "Tablones de madera oscura",
  "block.druidcraft.stripped_darkwood_wood": "Leño de madera oscura sin corteza",
  "block.druidcraft.darkwood_wood": "Leño de madera oscura",
  "block.druidcraft.darkwood_slab": "Losa de madera oscura",
  "block.druidcraft.darkwood_stairs": "Escaleras de madera oscura",
  "block.druidcraft.darkwood_fence": "Valla de madera oscura",
  "block.druidcraft.darkwood_fence_gate": "Puerta de valla de madera oscura",
  "block.druidcraft.darkwood_pressure_plate": "Placa de presión de madera oscura",
  "block.druidcraft.darkwood_button": "Botón de madera oscura",
  "block.druidcraft.darkwood_trapdoor": "Trampilla de madera oscura",
  "block.druidcraft.darkwood_door": "Puerta de madera oscura",
  "block.druidcraft.oak_beam": "Viga de roble",
  "block.druidcraft.spruce_beam": "Viga de abeto",
  "block.druidcraft.birch_beam": "Viga de abedul",
  "block.druidcraft.jungle_beam": "Viga de jungla",
  "block.druidcraft.acacia_beam": "Viga de acacia",
  "block.druidcraft.dark_oak_beam": "Viga de roble oscuro",
  "block.druidcraft.darkwood_beam": "Viga de madera oscura",
  "block.druidcraft.elder_beam": "Viga de saúco",
  "block.druidcraft.oak_small_beam": "Viga pequeña de roble",
  "block.druidcraft.spruce_small_beam": "Viga pequeña de abeto",
  "block.druidcraft.birch_small_beam": "Viga pequeña de abedul",
  "block.druidcraft.jungle_small_beam": "Viga pequeña de jungla",
  "block.druidcraft.acacia_small_beam": "Viga pequeña de acacia",
  "block.druidcraft.dark_oak_small_beam": "Viga pequeña de roble oscuro",
  "block.druidcraft.darkwood_small_beam": "Viga pequeña de madera oscura",
  "block.druidcraft.elder_small_beam": "Viga pequeña de saúco",
  "block.druidcraft.oak_panels": "Paneles de roble",
  "block.druidcraft.spruce_panels": "Paneles de abeto",
  "block.druidcraft.birch_panels": "Paneles de abedul",
  "block.druidcraft.jungle_panels": "Paneles de jungla",
  "block.druidcraft.acacia_panels": "Paneles de acacia",
  "block.druidcraft.dark_oak_panels": "Paneles de roble oscuro",
  "block.druidcraft.darkwood_panels": "Paneles de madera oscura",
  "block.druidcraft.elder_panels": "Paneles de saúco",
  "block.druidcraft.black_soulfire": "Fuego fatuo negro",
  "block.druidcraft.red_soulfire": "Fuego fatuo rojo",
  "block.druidcraft.green_soulfire": "Fuego fatuo verde",
  "block.druidcraft.brown_soulfire": "Fuego fatuo marrón",
  "block.druidcraft.blue_soulfire": "Fuego fatuo azul",
  "block.druidcraft.purple_soulfire": "Fuego fatuo morado",
  "block.druidcraft.cyan_soulfire": "Fuego fatuo cian",
  "block.druidcraft.light_gray_soulfire": "Fuego fatuo gris claro",
  "block.druidcraft.gray_soulfire": "Fuego fatuo gris",
  "block.druidcraft.pink_soulfire": "Fuego fatuo rosa",
  "block.druidcraft.lime_soulfire": "Fuego fatuo lima",
  "block.druidcraft.yellow_soulfire": "Fuego fatuo amarillo",
  "block.druidcraft.light_blue_soulfire": "Fuego fatuo azul claro",
  "block.druidcraft.magenta_soulfire": "Fuego fatuo magenta",
  "block.druidcraft.orange_soulfire": "Fuego fatuo naranja",
  "block.druidcraft.white_soulfire": "Fuego fatuo blanco",
  "block.druidcraft.wet_mud_bricks": "Ladrillos de barro húmedo",
  "block.druidcraft.wet_mud_bricks.description1": "Solo se pueden fabricar mientras estás en el agua.",
  "block.druidcraft.dry_mud_bricks": "Ladrillos de barro seco",
  "block.druidcraft.dry_mud_brick_slab": "Losa de ladrillos de barro seco",
  "block.druidcraft.dry_mud_brick_stairs": "Escaleras de ladrillos de barro seco",
  "block.druidcraft.dry_mud_brick_wall": "Muro de ladrillos de barro seco",
  "block.druidcraft.fiery_torch": "Antorcha ardiente",
  "block.druidcraft.fiery_torch.description1": "Un poco más brillante que la antorcha normal. ¡También resistente al agua!",
  "block.druidcraft.rope": "Cuerda",
  "block.druidcraft.elder_log": "Tronco de saúco",
  "block.druidcraft.stripped_elder_log": "Tronco de saúco sin corteza",
  "block.druidcraft.elder_planks": "Tablones de saúco",
  "block.druidcraft.stripped_elder_wood": "Leño de saúco sin corteza",
  "block.druidcraft.elder_slab": "Losa de saúco",
  "block.druidcraft.elder_stairs": "Escaleras de saúco",
  "block.druidcraft.elder_fence": "Valla de saúco",
  "block.druidcraft.elder_fence_gate": "Puerta de valla de saúco",
  "block.druidcraft.elder_pressure_plate": "Placa de presión de saúco",
  "block.druidcraft.elder_button": "Botón de saúco",
  "block.druidcraft.elder_trapdoor": "Trampilla de saúco",
  "block.druidcraft.elder_door": "Puerta de saúco",
  "block.druidcraft.elder_leaves": "Hojas de saúco",
  "block.druidcraft.elder_sapling": "Brote de saúco",
  "block.druidcraft.elder_wood": "Leño de saúco",
  "block.druidcraft.crate": "Caja",
  "block.druidcraft.crate.description1": "No puedes abrir cajas mientras tienes una en la mano.",
  "block.druidcraft.ceramic_lantern": "Linterna de cerámica",
  "block.druidcraft.growth_lamp": "Linterna de crecimiento",
  "block.druidcraft.growth_lamp.description1": "¡Acelera el crecimiento de plantas y animales dentro de un área 5x5x5!",
  "block.druidcraft.lavender": "Lavanda",
  "block.druidcraft.potted_lavender": "Lavanda en maceta",
  "block.druidcraft.potted_darkwood_sapling": "Brote de madera oscura en maceta",
  "block.druidcraft.potted_elder_sapling": "Brote de saúce en maceta",
  "block.druidcraft.black_bedroll": "Saco de dormir negro",
  "block.druidcraft.red_bedroll": "Saco de dormir rojo",
  "block.druidcraft.green_bedroll": "Saco de dormir verde",
  "block.druidcraft.brown_bedroll": "Saco de dormir marrón",
  "block.druidcraft.blue_bedroll": "Saco de dormir azul",
  "block.druidcraft.purple_bedroll": "Saco de dormir morado",
  "block.druidcraft.cyan_bedroll": "Saco de dormir cian",
  "block.druidcraft.light_gray_bedroll": "Saco de dormir gris claro",
  "block.druidcraft.gray_bedroll": "Saco de dormir gris",
  "block.druidcraft.pink_bedroll": "Saco de dormir rosa",
  "block.druidcraft.lime_bedroll": "Saco de dormir lima",
  "block.druidcraft.yellow_bedroll": "Saco de dormir amarillo",
  "block.druidcraft.light_blue_bedroll": "Saco de dormir azul claro",
  "block.druidcraft.magenta_bedroll": "Saco de dormir magenta",
  "block.druidcraft.orange_bedroll": "Saco de dormir naranja",
  "block.druidcraft.white_bedroll": "Saco de dormir blanco",
  "block.druidcraft.bedroll.description1": "¡Una forma de dormir que no te establecerá un punto de reaparición!",
  "block.druidcraft.bedroll.fail.monsters": "No puedes dormir ahora, hay monstruos cerca.",
  "block.druidcraft.bedroll.fail.dimension": "No puedes dormir en esta dimensión.",
  "block.druidcraft.bedroll.fail.time": "Solo puedes dormir de noche o durante tormentas eléctricas.",
  "block.druidcraft.bedroll.fail.placement": "No se puede poner un saco de dormir.",
  "block.druidcraft.woodcutter": "Cortador de madera",
  "block.druidcraft.debug_block": "Debug Block",
  "block.druidcraft.debug_block.description1": "Bloque de desarrollador, puede causar problemas en tu juego.",
  "block.druidcraft.elder_leaf_layer": "Fruta de saúco en descomposición",
  "block.druidcraft.turquoise_lunar_moth_lantern": "Linterna de polilla lunar turquesa",
  "block.druidcraft.lime_lunar_moth_lantern": "Linterna de polilla lunar lima",
  "block.druidcraft.orange_lunar_moth_lantern": "Linterna de polilla lunar naranja",
  "block.druidcraft.yellow_lunar_moth_lantern": "Linterna de polilla lunar amarilla",
  "block.druidcraft.white_lunar_moth_lantern": "Linterna de polilla lunar blanca",
  "block.druidcraft.pink_lunar_moth_lantern": "Linterna de polilla lunar rosa",
  "block.druidcraft.lunar_moth_lantern.description1": "Agáchate para colocar la linterna.",
  "block.druidcraft.brightstone_ore": "Mena de piedra brillante",
  "block.druidcraft.nether_fiery_glass_ore": "Mena de cristal ardiente del Nether",
  "block.druidcraft.hellkiln": "Hellkiln",
  "block.druidcraft.hellkiln_igniter": "Hellkiln Igniter",
  "block.druidcraft.infernal_flare": "Infernal Flare",

  "entity.druidcraft.dreadfish": "Pez del terror",
  "entity.druidcraft.beetle": "Escarabajo",
  "entity.druidcraft.lunar_moth": "Polilla lunar",

  "container.druidcraft.crate": "Caja pequeña",
  "container.druidcraft.crate_double": "Caja mediana",
  "container.druidcraft.crate_quad": "Caja grande",
  "container.druidcraft.crate_octo": "Caja enorme",
  "container.druidcraft.woodcutter": "Cortador de madera",
  "container.druidcraft.hellkiln": "Hellkiln",
  "container.druidcraft.hellkiln_igniter": "Hellkiln Igniter",

  "biome.druidcraft.darkwood_forest": "Darkwood Forest",

  "subtitles.druidcraft.item.bottle.fill": "Frasco rellenado",
  "subtitles.druidcraft.block.crate.open": "Caja abriéndose",
  "subtitles.druidcraft.block.crate.close": "Caja cerrándose",
  "subtitles.druidcraft.ui.woodcutter.take_result": "Cortador de madera usado",

  "itemGroup.druidcraft": "Druidcraft",
  "itemGroup.druidcraft_wip": "Druidcraft WIP - No Touchy!",

  "advancements.druidcraft.root.title": "Druidcraft",
  "advancements.druidcraft.root.description": "Busca por la hierba semillas de cáñamo",
  "advancements.druidcraft.grow_hemp.title": "Es industrial, ¡lo juro!",
  "advancements.druidcraft.grow_hemp.description": "Planta y cosecha cáñamo",
  "advancements.druidcraft.bone_armor.title": "Cráneo grueso",
  "advancements.druidcraft.bone_armor.description": "Ponte un casco de hueso",
  "advancements.druidcraft.make_mud_bricks.title": "Ensuciate",
  "advancements.druidcraft.make_mud_bricks.description": "Obtén ladrillos de barro",
  "advancements.druidcraft.fiery_torch.title": "¡Mejora de antorchas!",
  "advancements.druidcraft.fiery_torch.description": "Obtén mejores antorchas",
  "advancements.druidcraft.darkwood_forest.title": "Tiempos oscuros",
  "advancements.druidcraft.darkwood_forest.description": "Encuentra un bosque de madera oscura",
  "advancements.druidcraft.place_rope.title": "Atado",
  "advancements.druidcraft.place_rope.description": "Utiliza una cuerda",
  "advancements.druidcraft.collector.title": "Coleccionista",
  "advancements.druidcraft.collector.description": "Recolecta un bloque de piedra de luna, cristal ardiente, raíces de roca y ámbar",

  "block.druidcraft.old_crate.update": "Este bloque se ha actualizado. Rómpelo para obtener el bloque actualizado."
  
}

**Comment by Brun333rp** [comment]
dude, it doesn't work on this way. you need to open a pull request and upload the .json file with the translations.
