### ISSUE TITLE
"druidcraft encountered an error during the load_registries event phase"

### ISSUE THREAD

**Issue by gravysamich** [MysticMods/Druidcraft#11]
in the latest version of your mod i am getting this error whenever i start up minecraft.

i am using Druidcraft-1.14-0.2.31.jar. i don't have this issue with Druidcraft-1.14-0.2.3.jar.

pastebin of the log

https://pastebin.com/DCP3JvJd

**Comment by Gbergz** [comment]
Can confirm, i'm getting this aswell.

Mod-version: 1.14-0.2.31


error: [https://i.imgur.com/t4P8T8L.png](https://i.imgur.com/t4P8T8L.png)

**Comment by VulpTheHorseDog** [comment]
Fixed up in 0.2.32!
