### ISSUE TITLE
compatibility with corail tombstone's soul receptacle

### ISSUE THREAD

**Issue by lag42** [MysticMods/Druidcraft#12]
### General Information

**Describe the bug:**
corail tombstone's soul receptacle isn't picking up your tamed mobs, i'd like to be able to revive my beetles and dreadfish

**To Reproduce:**
1. tame beetle or dreadfish
2. kill that beetle or dreadfish with a soul receptacle in your inventory
3. notice how the soul receptacle is empty and the beetle or dreadfish will remain dead

**Expected behavior:**
the soul receptacle should recognize that beetle or dreadfish as a tamed mob and save it when it dies

***

### Environment Versions
java: 1.8.0_231

**Mystic Mods Versions**

- MysticalLib: 1.14.4-1.8.0
- Druidcraft: 1.14-0.2.32

**Other Versions:**
- Conflicting mod (if regarding mod integration): [corail tombstone](https://www.google.com/search?client=firefox-b-1-d&q=minecraft+corail+tombstone)
- Forge: 28.1.92
- Minecraft: 1.14.4
- Modpack (if available):

***

**Additional context (optional):**
quark's foxhound works so i think this is you not using the right flags that corail tombstone picks up on

**Comment by lag42** [comment]
corresponding issue on [corail tombstone's](https://github.com/Corail31/tombstone_lite/issues/105) repository

**Comment by noobanidus** [comment]
This has been resolved by Corail.
