### ISSUE TITLE
Butterfly tries to land on hemp and crashes the server 

### ISSUE THREAD

**Issue by Tander** [MysticMods/Druidcraft#14]
### General Information

**Describe the bug:**
Butterfly tries to land on hemp and crashes the server

**To Reproduce:**
1. Plant a lot of hemp
2. Spawn a lot of butterflies
3. Wait
4. Crash happen

***

### Environment Versions
Druidcraft-1.14-0.2.32
BloomfulV1.2.2
forge-28.1.107

**Crash Report (if available):**
https://hatebin.com/brpddfbkjp

***

### Additional Information

**Additional context (optional):**
It happens rarely, but still happens.

**Comment by noobanidus** [comment]
This is an issue with Bloomful. I've already submitted a PR which has a patch that fixes the issue.
