### ISSUE TITLE
Mixin compat issue with Draconic Evolution

### ISSUE THREAD

**Issue by border999** [MysticMods/Druidcraft#150]
Both your mod and Draconic Evolution are both trying to use a mixin that modifies a "Livingentitymixin." Hard crash on startup.

**To Reproduce:**
Install Druidcraft 1.18.2 and Draconic Evolution 1.18.2 together and attempt to startup.

### Environment Versions
Draconic-Evolution-1.18.2-3.0.27.515-universal
druidcraftrg-0.0.12

- Conflicting mod (if regarding mod integration):
- Forge: 1.18.2-forge--40.2.0
- Minecraft:  1.18.2

***

### Logging Information
https://gist.github.com/border999/ebef4c598fa87ca306fbf9438b007db0
https://gist.github.com/border999/8e75071187fb10d88ed69aea79718c53

**Comment by border999** [comment]
https://github.com/Draconic-Inc/BrandonsCore/issues/101

**Comment by border999** [comment]
https://github.com/Draconic-Inc/BrandonsCore/issues/101#issuecomment-1427159567

**Comment by brandon3055** [comment]
https://github.com/Draconic-Inc/BrandonsCore/issues/101#issuecomment-1427243585

**Comment by border999** [comment]
resolved
