### ISSUE TITLE
Many of druidcraft's items are missing in 1.18.2

### ISSUE THREAD

**Issue by cobaltlol** [MysticMods/Druidcraft#151]
### General Information

**Describe the bug:**

**To Reproduce:**

1. Just launch druidcraft on 1.18.2
2. -
3. -

**Expected behavior:**

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 
- Ecc...

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge:
- Minecraft:
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by VulpTheKangaFox** [comment]
The version you're running is a complete remake and a WIP. The old Druidcraft is not updated for 1.18.2.
