### ISSUE TITLE
Items, crates, and logs will not carry over to 1.18.2 from 1.16.5

### ISSUE THREAD

**Issue by ochoafabian18** [MysticMods/Druidcraft#152]
### General Information

**Describe the bug:**
Hello, I just downloaded and installed druidcraft for 1.18.2 and upgrading from 1.16.5, everything works fine except my items are gone since all of my crates from the old version along with my builds that contain dark wood logs are gone as well. The mod is installed succesfully, but I can't seem to move all of my items from the old druidcraft build to the new one. Has anyone else ever had this issue? I would love to get this fixed so I can play 1.18.2 with all of my builds from the last version.

**To Reproduce:**

1. First Step
2. First Step
3. First Step

**Expected behavior:**

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 
- Ecc...

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge:
- Minecraft:
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by VulpTheKangaFox** [comment]
You've updated from "Druidcraft" to "Druidcraft: Regrown" which is a complete remake essentially and also a very early WIP. It isn't the same mod so it won't carry things over.
