### ISSUE TITLE
Error in loading Tame a monster json

### ISSUE THREAD

**Issue by endcode-net** [MysticMods/Druidcraft#18]
### General Information
This seems to be a lack of data in the tame_a_monster.json

**Describe the bug:**

[22Jan2020 19:49:58.153] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager/]: Parsing error loading custom advancement druidcraft:druidcraft/unused/tame_a_monster: Invalid criterion trigger: druidcraft:tame_monster
**To Reproduce:**

1. First Step
Start up server.
2. First Step
Read the Log
3. First Step

**Expected behavior:**

***

### Environment Versions

Forge 1.14.4 20.1.114
**Mystic Mods Versions**
1.14-0.2.32

- MysticalLib: 
1.14.4-1.13.0
- Ecc...

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge:
- Minecraft:
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**
https://gist.github.com/endcode-net/46da7662ba47aa9110bc152577cb9758
**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by VulpTheHorseDog** [comment]
I'd moved that advancement to a folder called 'unused' but it still appears to want to load. It will be fixed sometime soon, and is only an error because there is no in-code event correlating to it yet.

**Comment by VulpTheHorseDog** [comment]
Json file has been removed now, and the log should no longer display this message as of v0.3.1.
