### ISSUE TITLE
Druidcraft (0.3.0) locks up minecraft on launch "Freezing Data"

### ISSUE THREAD

**Issue by Sos339** [MysticMods/Druidcraft#19]
After Installing the latest (0.3.0) of druidcraft, minecraft locks up at "Freezing data" before loading into the main menu

--Versions
Druidcraft-1.14-0.3.0
Forge 1.14.4 28.1.114
mysticallib-1.14.4-1.14.0

LOG:
https://pastebin.com/Ya4UGKU1

**Comment by noobanidus** [comment]
Hi there,

Currently I believe that Optifine cannot cope with the way beams and rope are set-up and handled. Something about the sheer number of potential states and combinations makes it just crap out when it gets to the point where it's parsing everything.

I know that Vulpie has a solution for this, which is a resource pack that you'll need to load before Optifine or before Druidcraft, and then restart with the relevant mod enabled. I unfortunately cannot find the resource pack at the minute, but when I do I'll attach it to this thread.

In the meantime, a solution is to disable Optifine.

**Comment by VulpTheHorseDog** [comment]
I actually left a note on the CurseForge page regarding this entire issue, I'd recommend checking it out.

**Comment by lag42** [comment]
rats just fixed a seemingly identical issue on their end, [maybe this is a lead](https://imgur.com/a/ysHtCJc)

**Comment by VulpTheHorseDog** [comment]
Not quite a lead. I already know there's too many block states. The issue is dividing that number is going to remove a huge amount of what makes rope good. I may need to divide it into separate blocks _and_ remove the waterlogging at minimum.

**Comment by VulpTheHorseDog** [comment]
The separate blocks being for knotted and unknotted.

**Comment by noobanidus** [comment]
https://github.com/Alex-the-666/Rats/commit/17274d97eff244486d510bdb96312ca32bcc6350 Commit in question

**Comment by VulpTheHorseDog** [comment]
I believe the Optifine issue to be fixed but it will need some testing.
