### ISSUE TITLE
Add Blueberries to Fruits Tag

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/Druidcraft#20]
**Describe your suggestion:**

- Currently, Blueberries only have a crops tag, but other mods, such as Pam's Harvestcraft and Simple Farming, also use the forge tags for fruits, such as `#forge:fruits` & `#forge:fruits/blueberries`. This would make it compatible with their recipes.
- Same for Elderberries, Pam's Harvestcraft uses the tag `#forge:fruits/elderberries` for it.

**Describe alternatives you've considered:**
N/A

**Comment by VulpTheHorseDog** [comment]
I'll see if I can get this added sometime soon!

**Comment by VulpTheHorseDog** [comment]
So I've received word that they would be automatically found inside the crops class instead, but I've still gone ahead and added these tags for v0.3.1, just in case.

**Comment by WenXin20** [comment]
Yeah, it's cause both Simple Farming and Harvestcraft uses the Fruit tag.

**Comment by noobanidus** [comment]
They should be generating their own fruit tag which automatically includes things based on the crops tag. If they aren't, that's a really poor action on their choice, as they're expecting people to follow a non-standard system.

**Comment by WenXin20** [comment]
Wouldn't that mean any vegetable crops or wheat would also end up included in the fruits tag?

**Comment by noobanidus** [comment]
No, I mean, if there is:

`forge:crops/blueberries`
`forge:crops/strawberries`

presumably then it follows that

`forge:fruit/blueberries` should be generated as a tag that also contains `forge:crops/blueberries`
likewise `forge:fruit/strawberries` should be also contain `forge:crops/strawberries`

ergo, `forge:fruit` would contain all of the `forge:fruit/*` tags.

In this way, there's the separate of fruits/vegetables, but automatically including the *standard* `forge:crops` tag bypassing having to get other mods to add their crops to non-standard tags.

**Comment by VulpTheHorseDog** [comment]
I mean I don't recall that simple farming used this method, so for the time being at least, I've got that fixed up.

**Comment by noobanidus** [comment]
By this I meant, if you implement a parallel standard you should set up a system by which other people don't have to ascribe to it -- you can just naturally include the standardised-format Forge tags that you want to include in fruits.

It was more an explanation of "the mod that uses forge:fruit should do so in such a way that only it *has* to do that, and all other mods just use forge:crop as standard, and it Just Works".

**Comment by WenXin20** [comment]
Ah, I see, thanks.
