### ISSUE TITLE
Ceramic Lanterns have an misaligned hitbox

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/Druidcraft#21]
### General Information

**Describe the bug:**
- The hitbox of the Ceramic Lantern is misaligned, as seen in the image below.

**To Reproduce:**

1. Place a Ceramic Lantern.
2. Look at it.

**Expected behavior:**
- The hitbox should not be misaligned.

***

### Environment Versions

**Mystic Mods Versions**

- `MysticalLib: v1.14.0`
- `Druidcraft: v0.3.0`

**Other Versions:**
- `Forge: v28.2.0`
- `Minecraft: v1.14.4`
- Modpack (if available): N/A

***

### Additional Information

**Screenshots:**
![2020-02-09_19 44 36](https://user-images.githubusercontent.com/12000593/74116036-50fa6500-4b77-11ea-8554-db859f3e96de.png)

**Comment by VulpTheHorseDog** [comment]
Ooh, yeah I saw this and swore I fixed it. I'll get a fix out sometime soon.

**Comment by VulpTheHorseDog** [comment]
Turns out I wasn't using the ceramic lantern class, but instead the base lantern class, hence why the original fix I did changed nothing. Should be fine now in v0.3.1.
