### ISSUE TITLE
Elderflowers have missing texture instead of transparency

### ISSUE THREAD

**Issue by puffpastri** [MysticMods/Druidcraft#22]
### General Information

**Describe the bug:**
When elderflowers are growing on a tree, they have a missing texture displayed instead of transparency behind them.

**To Reproduce:**
1. Find elder tree.
2. Look at the flowers growing on the tree.

**Expected behavior:**
The pink and black texture should not be displayed, and the elderflower texture should be transparent instead.

***

### Environment Versions

**Mystic Mods Versions**
- `Mystical lib 1.14.0`
- `Druidcraft 0.3.0`

**Other Versions:**
- `Forge 28.2.0`
- `Minecraft 1.14.4`
- Modpack (if available): No modpack

***

### Additional Information
**Screenshots (if available):**
![2020-02-15_23 29 29](https://user-images.githubusercontent.com/10354850/74588005-07b18600-504d-11ea-960c-386c2afacda1.png)

**Comment by WenXin20** [comment]
It also cannot be seen by Hwyla.

**Comment by VulpTheHorseDog** [comment]
The flower/berry texture _is_ transparent, but there's a backdrop behind it of a little tuft of leaves. For some reason the lowercase naming of the leaves had reverted to the capitals I had mistakenly used a long while ago once I'd built the version. I've fixed this up now in v0.3.1.
