### ISSUE TITLE
Expanding the dreadfish

### ISSUE THREAD

**Issue by Terravolt14** [MysticMods/Druidcraft#26]
- buff its speed

- better flight AI

- maybe spectral bubble particle attacks...

- a patrol AI

**Comment by VulpTheHorseDog** [comment]
The speed and flight AI are things that need done, yes. I don't have the know-how to pull it off just yet however. And bubble attacks might be a possibility but there is something similar planned for another creature and I don't want things overlapping.

**Comment by noobanidus** [comment]
Given they spawn in cold biomes and aren't actually underwater or really fish at all, some sort of cold-based ice attack might be better than bubbles. 

The problem with AI of any creature is that the more complex AIs there are on your server, the more time-consuming each tick becomes; if it were just for tamed Dreadfish, then this AI would only be accessible for them (which would make sense). However, there lies the question of how to best transition them between modes (follow, patrol, etc).

**Comment by Terravolt14** [comment]
how do I heal my dreadfish?

**Comment by VulpTheHorseDog** [comment]
Using bones on it will repair it's skeleton. Closing the suggestion as giving the dreadfish better AI and such is something planned, but requires me to know more before executing.
