### ISSUE TITLE
Hemp seeds prevent tall grass drop

### ISSUE THREAD

**Issue by AlexProGear** [MysticMods/Druidcraft#27]
When using shears to harvest tall grass, sometimes hemp seeds pop out, and grass doesn't drop (basically, when seed gets random chance to drop, it replaces grass loot table, I think).
What I expected to happen:
Grass drops 100% of the times I'm shearing it
What happens:
It's not 100%
Mod is on the latest version of mc 1.14.4
Forge version 28.2.0

**Comment by VulpTheHorseDog** [comment]
Should be fixed as of the next version!
