### ISSUE TITLE
Small Beams compatibility Issue with 'fake' worlds

### ISSUE THREAD

**Issue by simibubi** [MysticMods/Druidcraft#28]
Druidcrafts' small beams perform an unchecked cast from IWorld to World in updatePostPlacement, is this really necessary? Afaik, IWorld should have enough information for selecting the correct blockstate.
With this cast in place, these blocks will not behave well with schematic previewers or other non-physical worlds. An example would be [The Mighty Architect](https://www.curseforge.com/minecraft/mc-mods/the-mighty-architect).

<https://github.com/MysticMods/Druidcraft/blob/53afc73c9da3285cf046fa42fd77d6edbaffbfc0/src/main/java/com/vulp/druidcraft/blocks/SmallBeamBlock.java#L181>

Cheers!

**Comment by noobanidus** [comment]
`calculateState` can probably be converted to just accept IWorld. I believe it should be sufficient.

**Comment by VulpTheHorseDog** [comment]
I think it's fixed up now? Correct me if I'm wrong. I'm pretty sure it wouldn't allow me to use IWorld in that parameter, so I've used IWorld#getWorld instead. If it's an issue, let me know.

**Comment by VulpTheHorseDog** [comment]
Oop, nevermind, was an easy fix anyway. Should be packed into the next build.
