### ISSUE TITLE
Crash when taking out bedroll to sleep

### ISSUE THREAD

**Issue by maham** [MysticMods/Druidcraft#31]
### General Information

**Describe the bug:**
I was waiting for the sun to set to sleep and chose the bedroll on the hotbar. Game crashed to desktop.

**To Reproduce:**
See description. No attempt to reproduce have been made.

**Expected behavior:**
No crash hopefully

***

### Environment Versions
MC: 1.14.4
Forge: 28.2.3
Druidcraft: 0.4.0-dev0.6
MysticalLib: 1.16.1
Modpack: OpenDevCraft 7.02

### Logging Information
Log: https://paste.ee/p/xSzKQ
Crash Report: https://pastebin.com/wMfHZrws

**Comment by maham** [comment]
Another crash like the first just happened when I tried to open a chest with the bedroll in hand. Could be that I tried to right click something with it in hand last time too. New log: https://paste.ee/p/VyV9w

**Comment by VulpTheHorseDog** [comment]
I think this _should_ be fixed as of the latest dev version. Let me know how it goes!
