### ISSUE TITLE
[1.15.2] Black Soulfire

### ISSUE THREAD

**Issue by TheUntamed** [MysticMods/Druidcraft#32]
The texture for the black Soulfire is not filled. I'm not sure if that's intended because all other Soulfires are filled and this one looks a bit out of place.

**Comment by VulpTheHorseDog** [comment]
This was intentional, the way the rendering for the particles work, the black soulfire renders near transparent when placed in the world, so it was textured to represent it properly.

That said, I'm considering changing particles, so we'll see if that remains a thing in future.
