### ISSUE TITLE
[CRASH] Incompatibility with  BonsaiTrees

### ISSUE THREAD

**Issue by Tander** [MysticMods/Druidcraft#33]
### General Information

Client crashes when I try to use these two mods together.

### Environment Versions

Forge: net.minecraftforge:31.2.0
Mod List:
Druidcraft-1.14-0.3.1.jar
libnonymous-1.15.2-1.1.1.5.jar (lib for bonsaitrees)
BonsaiTrees-2.1.2.6.jar Bonsai Trees 2

***

### Logging Information
Crashlog:
https://pastebin.com/pUH0FNWn

***

**Comment by noobanidus** [comment]
Please post your entire `latest.log`. This error occurs when there has been an issue at some previous point in initialization, and doesn't actually reflect what the issue is.

**Comment by Tander** [comment]
Here: https://pastebin.com/WCjWjtnA

**Comment by noobanidus** [comment]
Uh... you appear to be using Druidcraft 1.14 0.3.1 in 1.15.2, 

a) The most recent 1.14.4 version of Druidcraft is 0.4.0
b) There is a 1.15.2 release of Druidcraft which is also version 0.4.0

I'm not sure why it isn't causing a more succinct error message, but installing a 1.14.4 mod in a 1.15.2 environment isn't going to do anything.

**Comment by Tander** [comment]
Twitch launcher installed it automatically. Sometimes it happens, maybe it doesn't expect to see identical versions for different MC versions or something like this.

**Comment by noobanidus** [comment]
0.3.1 is still a very, very old version. I'd recommend spamming the "Refresh" button before installing anything in a pack just in case you have a stale version of mods.

**Comment by noobanidus** [comment]
(And failing that, go into the mod itself and go to the "Versions" tab.)
