### ISSUE TITLE
Crash during feature placement

### ISSUE THREAD

**Issue by yurifel** [MysticMods/Druidcraft#39]
### General Information

**Describe the bug:**
The game is crashing while generating new chunks.

**To Reproduce:**
1. Install Druidcraft-1.15-0.4.0
2. Create a new world
3. If successful, fly around for a bit

***

### Environment Versions

**Mystic Mods Versions**

- Druidcraft-1.15-0.4.0

**Other Versions:**
- Forge: 31.2.9
- Minecraft: 1.15.2
- No other mods installed

***

### Logging Information

**Crash Report (if available):**
https://pastebin.com/DcmuzWb4

**Latest Log (if necessary):**
https://pastebin.com/RLbkyYK4

**Another log featuring the same crash during initial world generation**
https://pastebin.com/Ayw148uS

**Comment by VulpTheHorseDog** [comment]
Already fixed up in the code, will be releasing the fixed version soon!
