### ISSUE TITLE
[1.15.2] JEI '@druidcraft' is super unorganized.

### ISSUE THREAD

**Issue by Gbergz** [MysticMods/Druidcraft#43]
Title^

MC Version: 1.15.2
Druicraft Version: 1.15-0.4.1
Forge Version: 31.2.19

Preview:
![jeidrui](https://user-images.githubusercontent.com/26634554/84304365-b0ce4000-ab58-11ea-944c-cdb033c7509f.PNG)

Could this be fixed somehow?
Thanks for a great mod btw!
- Gbergz

**Comment by Gbergz** [comment]
It happens on my existing world, but it's a development world as I'm creating a modpack. Just created a new world to see if it's still unorganized. It was not. Thanks for telling me that! 👍

**Comment by noobanidus** [comment]
No worries! Just something to be aware of, that adding mods to existing worlds messes things u p, especially JEI :/
