### ISSUE TITLE
Crash while growing darkwood tree

### ISSUE THREAD

**Issue by Divineaspect** [MysticMods/Druidcraft#44]
### General Information

**Describe the bug:**
Crash while growing darkwood tree

**To Reproduce:**

1. Place 2x2 grids of darkwood saplings

**Expected behavior:**
Trees to grow

***

###Versions
- Forge: 31.2.19
- Minecraft: 1.15.2
- Modpack (if available):

***

### Logging Information
**Crash Report (if available):**
https://gist.github.com/belathus/72af29e84d9f0e1ce1371cecb88d54c6

**Latest Log (if necessary):**

**Comment by caligator** [comment]
likewise having the same issue, crippled my server save for Oops All Mods.
User planted a 2x2 darkwood saplings set. 

> https://hastebin.com/atacugefuh.rb

**Comment by VulpTheHorseDog** [comment]
Huh, that's odd. So when testing, the 1x1 doesn't work, nor does the 2x2. No crashing is present, just a lack of a tree and the loss of a sapling. I'm working on a fix right now.

**Comment by VulpTheHorseDog** [comment]
All fixed, I would assume! Available in 0.4.2!
