### ISSUE TITLE
Darkwood Forest Crash

### ISSUE THREAD

**Issue by Drakoflame** [MysticMods/Druidcraft#45]
### General Information

**Describe the bug:**
Game crashes when trying to generate trees for Darkwood Forest

**To Reproduce:**
1. Create world (I use several mods, seed might not work the same) with seed "Balloons"
2. Head ESE to village
3. Walk into village until crash

**Expected behavior:**
Game not crashing

***

### Environment Versions
Forge: 31.2.20
Druidcraft: 1.15.2-0.4.2
**Mystic Mods Versions**

        QuarkOddities-1.15.2
        inventorysorter-1.15.2-17.0.0
        TrashSlot_1.15.2-11.0.0
        mining-helmet-1.15.2-1.0.8
        berry_good-2.0.0
        upsizer-mc1.15.2-5.1
        dungeon_armors_1.0.0
        jei-1.15.2-6.0.0.4
        OptiForge-MC1.15.2-0.1.24
        metalbarrels-2.1
        Druidcraft-1.15-0.4.2
        AttributeFix-1.15.2-7.0.2
        Abnormals-Core-1.15.2-1.0.6
        Buzzier-Bees-1.15.2-1.5.1
        rofl2leather-1.15.2-3.0.0
        Upgrade-Aquatic-1.15.2-v1.6.1
        invtweaks-1.15.2-2.0.4
        [1.15.2] Armor Status HUD v1.3.4
        create-mc1.15.2_v0.2.4d
        Waystones_1.15.2-6.0.1
        XaerosWorldMap_1.6.4_Forge_1.15.2
        mgui-1.15.2-2.1.1
        LightOverlay-4.6.1
        CookingForBlockheads_1.15.2-8.0.2
        Placebo-1.15.2-3.0.2
        SereneSeasons-1.15.2-3.0.0.72
        Bookshelf-1.15.2-5.6.40
        Coins-1.15.2-1.0.1
        The-Endergetic-Expansion-1.15.2-v1.3.1
        snowundertrees-1.15.2-v1.1.1
        randompatches-1.15.2-1.21.1.2
        Apotheosis-1.15.2-3.1.2
        sandbag-1.15.2-1.0.0
        mcw-doors-1.0.0-mc1.15.2
        ironshulkerboxes-1.15.2-4.0.1
        Hwyla-forge-1.10.8-B72_1.15.2
        walljump-forge-1.15.2-1.3.5
        SnowRealMagic-1.15.2-1.7.5
        Kiwi-1.15.2-2.7.1
        traverse-1.15.2-3.2.0
        1.15.2.BobLib.v0.1.8
        mysticallib-1.15.2-2.0.0
        ironchest-1.15.2-10.0.3
        corpse-1.15.2-1.0.6
        torchmaster-2.1.1-rc0
        swingthroughgrass-1.15.2-1.4.0
        compactores-1.15.2-2.1.2
        Jade-1.15.2-1.1.2
        valhelsia_structures-15.0.3a
        forbidden_arcanus-1.15.2-1.3.1
        packedup-1.0.12-mc1.15
        simplefarming-1.15.2-1.2.9
        curios-FORGE-1.15.2-2.0.2.4
        tetra-1.15.2-2.11.0
        Patchouli-1.15.2-1.2-34
        corail_woodcutter-1.1.3-1.15.2
        Xaeros_Minimap_20.14.0_Forge_1.15.2
        carrotslib-mc1.15.2-2.5
        vanillafoodpantry-mc1.15.2-5.5
        config-2-3.0.jar Cloth Config v2 API 
        autumnity-1.3.2-1.15.2
        polymorph-FORGE-1.15.2-0.2
        AutoRegLib-1.5-40
        Quark-r2.1-245
        OreExcavation-1.7.151
        usefulhats-1.6.0-1.15.1
        obfuscate-0.4.3-1.15.2
        vehicle-mod-0.44.0-1.15.2.jar MrCrayfish's Vehicle Mod
        malilib-forge-1.15.2-0.10.0-dev.20+beta.1
        guncus-1.15.2-1.3.jar Gun Customization 
        noRecipeBook_v1.5.4formc1.15.2
        mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs 
        AppleSkin-mc1.15.2-forge-1.0.13
        nwis-1.3.1.jar Not What It Seems
        mcw-furniture-1.0.1-mc1.15.1+1.15.2.jar Macaw's Furnitures
        itemscroller-forge-1.15.2-0.15.0-dev.20200412.215325
        Charm-1.15.2-1.5.9
        Strange-1.15.2-1.0.0-beta.5.hotfix1
        Charmonium-1.15.2-1.0.1
        Covalent-1.15.2-1.0.2
        toms_storage-1.1.2
        FastLeafDecay-v22
        CosmeticArmorReworked-1.15.2-v3a
        overloadedarmorbar-4.0.0.jar Overloaded Armor Bar
        WailaHarvestability-mc1.15.2-1.1.12
        OpenLoader-1.15.2-4.0.5

**Other Versions:**
       preview_OptiFine_1.15.2_HD_U_G1_pre23

***

### Logging Information
https://pastebin.com/n2M07i76

**Crash Report (if available):**
https://pastebin.com/TPqFQ80M (crash)

**Latest Log (if necessary):**
(same log in #logging Information)

**Comment by Drakoflame** [comment]
Update: Rolled back to 0.4.1 version of Druidcraft, no crash happens

**Comment by NJL5390** [comment]
Can confirm that I am also getting this same issue, whenever I go near a Darkwood Forest.

**Comment by DoCharlcate** [comment]
Can confirm same issue here playing 1.15.2, forge: 31.2.20

**Comment by Vaelzan** [comment]
This occurs with both 0.4.1 and 0.4.2 - tested on Forge 31.2.9.

**Comment by Drakoflame** [comment]
> This occurs with both 0.4.1 and 0.4.2 - tested on Forge 31.2.9.

Try updating to 31.2.20, because I'm using 0.4.1 on the exact same world and have not crashed from it

**Comment by Vaelzan** [comment]
I think I was mixing it up with a very similar but different crash anyway, I can see that one crash is resolved but the other is not, and each version has one or the other issue.

**Comment by VulpTheHorseDog** [comment]
Should be fixed up as of 0.4.21!
