### ISSUE TITLE
[1.15.2] Crates duplicate / replace items when sorted (Quark / Inventory Sorter)

### ISSUE THREAD

**Issue by Vaelzan** [MysticMods/Druidcraft#46]
### General Information

**Describe the bug:**
The Large Crate (but it appears no other size) can duplicate or replace existing item stacks when sorted using Quark's sort button or CPW's Inventory Sorter mod. This specifically happens when items are in the 29th slot onwards, and stops when the first 27 slots are completely full.

**To Reproduce:**
1. Build a Large Crate
2. Add some items, ensuring that some are towards the bottom of the crate (29th slot or further).
3. Middle click (default hotkey) with Inventory Sorter installed, or click Sort Container with Quark installed.
4. Watch as more items appear each time, replacing some existing item stacks entirely, and stopping once the 27th slot is full.

**Expected behavior:**
Sorting consistent with the Small, Medium and Huge Crates.

### Environment Versions

**Mystic Mods Versions**
Druidcraft-1.15-0.4.1 (am updating shortly, but I can't see any changes to crate code so this report should still be valid)

**Other Versions:**
- Conflicting mod (if regarding mod integration): Quark-r2.1-245, inventorysorter-1.15.2-17.0.0
- Other mods you think could cause issues: N/A.
- Forge: Forge-1.15-31.2.9
- Minecraft: 1.15.2
- Modpack (if available): WIP Valhelsia pack - not public yet.

***

### Logging Information

**Crash Report (if available):**
N/A, no crash.

**Latest Log (if necessary):**
N/A, nothing of note was logged.

***

### Additional Information
**Screenshots (if available):**
A screenshot won't achieve much but if required I can make a video clip later of the bug in action. I Just need to get some recording software. :)

**Comment by Vaelzan** [comment]
Update: It appears that the items in later slots are placed in the earlier slots, but not removed from the later slots, thus duplicating them. This placement can also replace existing item stacks in some cases.

**Comment by caligator** [comment]
Having the same issue myself, can reproduce in the same way. using quark as my sorting mod

**Comment by winnetrie83** [comment]
I see this hasn't been fixed yet. Here is a video : https://youtu.be/Z9kVeBRJc_E

**Comment by loleq2105** [comment]
I am experiencing this issue as well. This absolutely game-breaking bug can't stay in this mod any longer, as you can see in winnetrie's video, any item can be duplicated. If this is too complex of an issue, you can always just temporarily disable large crate multiblocks.

**Comment by noobanidus** [comment]
> This absolutely game-breaking bug can't stay in this mod any longer,

I appreciate your passion on the matter, but if you are truly negatively and urgently impacted by this, I would suggest not waiting for the next Druidcraft release. Instead, you can use a datapack to disable the recipe for making crates, and then use whatever administrative tools you have at your disposal to remove crates already in the world.

As it stands, I've just finalised the conversion of the Crates to using a more simplified system of combined IItemHandlers, which should prevent this issue from occurring, but we'll be sure to test it before release.

**Comment by noobanidus** [comment]
This should be in the most recent release. Please ensure you're using the most recent release as a stupid typo I made in the one previous to that (potentially archived now) was causing crates to lose their inventories. If you have any other issues with it, please open a new issue -- as it would be a completely different part of the code base.
