### ISSUE TITLE
Terraforged does not generate Druidcraft's Darkwood Forest

### ISSUE THREAD

**Issue by lamoyrl90** [MysticMods/Druidcraft#49]
Terraforged doesn't seem to produce Darkwood Forests from Druidcraft. I generated multiple worlds, setting biome size to 50, and none of them had a Darkwood Forest within 10,000 blocks of spawn.

As soon as I generated a Default worldtype, I found one within 50 blocks of spawn.

Tested using Nature's Compass, Druidcraft 0.4.21 and Terraforged 0.0.14 on MC 1.15.2

I'm not sure whether the cause of this lies in Druidcraft or Terraforged, so I'm posting this to both mods' pages.

Terraforged issues post: https://github.com/TerraForged/TerraForged/issues/211

**Comment by dags-** [comment]
Hi, this can be resolved by marking the biome(s) with the OVERWORLD BiomeDictionary.Type :]

More information here:
https://github.com/TerraForged/TerraForged/wiki/Mod:-Biomes

**Comment by lamoyrl90** [comment]
Thanks for the quick solution. I'm gonna stick this in a data pack til it gets implemented in the mod!

**Comment by noobanidus** [comment]
This has been updated to include the OVERWORLD tag in development. I'm unsure if any of the current releases contain it.

**Comment by Akaitatsu** [comment]
> 
> 
> This has been updated to include the OVERWORLD tag in development. I'm unsure if any of the current releases contain it.

Any idea when this is going to be released? You might want to leave this issue open until the fix has been released. Closing it makes it difficult to find and you're likely to get duplicate issue reports.

**Comment by noobanidus** [comment]
That's an extremely valid point that I hadn't considered, reopening so it's visible.

**Comment by noobanidus** [comment]
As of the most recent release this should be fixed. If the biomes still do not function with Terraforged, please open a new issue as it likely means that there is a problem with something else.

**Comment by Akaitatsu** [comment]
Tested with 0.4.41 and Darkwood Forest is being generated. Thank you!
