### ISSUE TITLE
Advancements page background default

### ISSUE THREAD

**Issue by MelanX** [MysticMods/Druidcraft#5]
I don't know if it's intended or not but the background is the default texture.
![image](https://user-images.githubusercontent.com/26039509/66713754-13dfbb00-edaf-11e9-8d90-0fbe908f6640.png)
The texture is from pack Unstable 1.14-1.10.0

Mod version: 0.1.31

**Comment by duely** [comment]
Thanks for the heads-up! Looks like there was a typo in a file, or a misnamed file. It should be fixed in the next release.
