### ISSUE TITLE
Beetle Spawn Conditions

### ISSUE THREAD

**Issue by MaxAstro** [MysticMods/Druidcraft#53]
**Describe your suggestion:**
Beetles seem to spawn, although rarely, regardless of light level.  Hostile mobs that spawn regardless of light level are not cool.  Angry beetles spawning in the middle of your base is annoying.  :(  Could they be changed to respect light level for spawning?

**Describe alternatives you've considered:**
Alternatively, making them not hostile unless attacked, maybe... but they are big and seem like they would get in the way.  Would prefer if they just didn't spawn in the light.

**Additional context:**
They do look cool though.  Just don't want to die while I'm afk due to bad luck...

**Comment by VulpTheHorseDog** [comment]
They are being fixed up next update, don't you worry!

**Comment by VulpTheHorseDog** [comment]
Been a while but an update on this. Beetles will be getting somewhat reworked in 1.16. I'll allow configuration of beetle spawn blocks in the configs for 1.15, but come 1.16's following updates the beetle issues should be all nicely resolved.

1.15 temp fix will be out in the next day or so.

**Comment by VulpTheHorseDog** [comment]
On second thought, I'm not going to touch the beetle spawn configs. They only spawn on grass as of the upcoming build, and I can't imagine many people needing to change that.

**Comment by halfpastfouram** [comment]
Why can't you imagine that? My villages get killed by them and there is no way to prevent them from spawning now, is there?

**Comment by VulpTheHorseDog** [comment]
Yes there is, their spawns can be disabled in configs. Life has been busy, I'm still working on the update that includes the beetle rework. Either be patient, use something other than default grass, change configs, or stop using the mod until it's fixed.
