### ISSUE TITLE
Elderflower cordial recipe oddity

### ISSUE THREAD

**Issue by BlueLadyAces** [MysticMods/Druidcraft#56]
### General Information

**Describe the bug:**
The elderflower cordial recipe shows up in JEI as requiring Uncraftable potion.

**To Reproduce:**
1. Open JEI
2. Find Elderflower / Elderflower cordial
3. Click Elderflower cordial to see its recipe or right click Elderflower to see its uses

**Expected behavior:**
The recipe either asking for a potion or bottle of water that can actually be obtained legitimately in game

***

### Environment Versions
**Mystic Mods Versions**
- Druidcraft 1.15-0.4.21

**Other Versions:**
- JEI: 6.0.1.5
- Forge: 31.2.31
- Minecraft: 1.15.2
- Modpack (if available): Valhelsia 2 (slightly modified to add mostly QoL UI/control mods, along with Druidcraft because I was eager to try it out)
- Full mod list (generated by bat file in mods directory): https://pastebin.com/CGSqDPbq

### Additional Information
**Screenshots (if available):**
![2020-07-11_15 07 17](https://user-images.githubusercontent.com/7568427/87224784-5a873380-c388-11ea-8409-fb661e9289c5.png)

**Comment by ace10102** [comment]
Pretty sure that's just how jei indicates that any potion is valid, including water bottles

**Comment by BlueLadyAces** [comment]
> Pretty sure that's just how jei indicates that any potion is valid, including water bottles

Confirmed that it works with water bottle; apparently JEI is just silly. Thanks for the lead!
