### ISSUE TITLE
No Tree Punching Compat.

### ISSUE THREAD

**Issue by Jollyolsport** [MysticMods/Druidcraft#57]
NTP works to where a block can only be broken by its respective tool, unless no possible tool could be used I.E. torches, bedrolls, etc. However, all wooden blocks and their subgroups I.E. fences, doors, crates, etc. cannot at all be broken , so I'm assuming they arent assigned any designated tool for harvesting? Which in this case would be an axe? but that doesnt seem to work. All other blocks like ore, ore blocks, woodcutter, leaves. can be broken, with the right tool. 

Druidcraft-1.15-0.4.21

-No Tree Punching
- Forge: 31.2.31
- Minecraft:1.15.2

**Comment by noobanidus** [comment]
I'd recommend talking to the No Tree Punching team and find out exactly what the requirements are; they're more likely to understand or know why this isn't working.

**Comment by alcatrazEscapee** [comment]
Hi, No Tree Punching "team" here. You set `harvestTool` but not `harvestLevel` here. 

https://github.com/MysticMods/Druidcraft/blob/71cc817bdd822d160a224601f1a4c2342504c5dc/src/main/java/com/vulp/druidcraft/DruidcraftRegistry.java#L278

Fortunately, this is something I can expect to happen and correctly handle by assuming it just means the modder in question forgot to assign a harvest level and just default it to 0.

**Comment by noobanidus** [comment]
Ah, thanks for the note; I'll try to make a pass through and make sure the harvest levels are set to 0.
