### ISSUE TITLE
Hemp seeds can be fed to chickens by hand but not by quark's feeding trough

### ISSUE THREAD

**Issue by LordMZTE** [MysticMods/Druidcraft#58]
### General Information

**Describe the bug:**
clicking a chicken with hemp seeds will work, however using a feeding through from the quark mod doesnt.

The quark feeding trough will check if the item is valid by calling AnimalEntity#isBreedingItem. chicken entity checks that by testing if a static field called net.minecraft.entity.passive.ChickenEntity#TEMPTATION_ITEMS which is a Ingredient contains the item. this field could be access-transformed and modified (for example by calling Ingredient#merge in order to create a new instance with the chicken's current breeding items plus hemp seeds)

***

### Environment Versions
???

**Mystic Mods Versions**

- MysticalLib: not installed
- druidcraft 0.4.21

**Other Versions:**
- Other mods you think could cause issues: quark (unlikely)
- Forge: 31.2.30
- Minecraft: 1.15.2
- Modpack (if available): valhelsia 2

**Comment by LordMZTE** [comment]
It may be slightly different since i checked this on 1.16 but there shouldn't be major differences

**Comment by noobanidus** [comment]
Yeah, in 1.15.2 it seems to be:

```java
   private static final Ingredient TEMPTATION_ITEMS = Ingredient.fromItems(Items.WHEAT_SEEDS, Items.MELON_SEEDS, Items.PUMPKIN_SEEDS, Items.BEETROOT_SEEDS);
```

which is unfortunate.

It would be nice if this was instead an item tag.

**Comment by LordMZTE** [comment]
Can't the final be removed? If so then it would be possible to add stuff

**Comment by noobanidus** [comment]
Oh, it could easily be removed with an access transformer, just bemoaning the fact that Minecraft has introduced an entire new tag system but has failed absolutely to use it when they could (i.e., Ingredient.fromTag).

**Comment by LordMZTE** [comment]
Yep I agree. But that means that this could be implemented
