### ISSUE TITLE
[1.15.2] JEI support for Woodcutter

### ISSUE THREAD

**Issue by TheUntamed** [MysticMods/Druidcraft#59]
it's not possible to view the recipes of the woodcutter  (the recipes you can do with the woodcutter not the recipe for the woodcutter itself). Wood be neat if that could be added.

**Comment by noobanidus** [comment]
JEI currently doesn't support the stonecutter (at least in 1.15.2, I think?), unless functionality was recently added, so it might be a little more work. I've been hoping stonecutter support would become available so it could be more easily hijacked for use-cases like this.

**Comment by TheUntamed** [comment]
For the vanilla stonecutter I can view all recipes in 1.15.2
![Screenshot_1](https://user-images.githubusercontent.com/48363903/88038979-4b05a880-cb47-11ea-95a0-be750d6ab3ae.jpg)

**Comment by noobanidus** [comment]
Oh nice, it should be possible to just copy that then.

**Comment by VulpTheHorseDog** [comment]
All ready to go for the next update! Not long now.
