### ISSUE TITLE
Problem with light sourses 

### ISSUE THREAD

**Issue by guide-for-you** [MysticMods/Druidcraft#6]
There we have picture that I made for proof
![2019-11-06_21 15 57](https://user-images.githubusercontent.com/53404970/68330007-2bbf0c00-00db-11ea-8116-6d0c9d3129b8.png)
On this picture dreadfish don't have soulfire,soulfire don't have texture and just fire glass torch

**Comment by VulpTheHorseDog** [comment]
Fixed, was an issue with older versions of forge being used.
