### ISSUE TITLE
Ropes not waterlogged properly

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/Druidcraft#60]
### General Information

**Describe the bug:**
- Ropes placed underwater are not waterlogged.

**To Reproduce:**

1. Place ropes underwater

**Expected behavior:**
- Should be waterlogged

***

### Environment Versions

**Mystic Mods Versions**

- `Mystical Lib: v2.0.1`
- `Druidcraft: v0.4.21`

**Other Versions:**
- `Forge: v31.2.31`
- `Minecraft: v1.15.2`

***

### Additional Information
**Screenshots:**

![2020-07-21_16 04 38](https://user-images.githubusercontent.com/12000593/88107306-7f3f9000-cb6c-11ea-9001-cb8fc981ac94.png)

**Comment by VulpTheHorseDog** [comment]
Weird, I'll have to look into that.

**Comment by VulpTheHorseDog** [comment]
Fixed for version 0.4.4 coming out soon.

**Comment by WenXin20** [comment]
Alright, thanks!
