### ISSUE TITLE
Bounding box for lunar moth lanterns on rope incorrect

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/Druidcraft#61]
### General Information

**Describe the bug:**
- Moth Lanterns consumed when moths are released in creative.
- Lanterns also have a disconnected hitbox when placed on a rope.

**To Reproduce:**

1. Release a moth in creative
2. Also try placing on a rope

**Expected behavior:**
- Item shouldn't be consumed in creative.

***

### Environment Versions

**Mystic Mods Versions**

- `Mystical Lib: v2.0.1`
- `Druidcraft: v0.4.21`

**Other Versions:**
- `Forge: v31.2.31`
- `Minecraft: v1.15.2`

***

### Additional Information
**Screenshots (if available):**
![2020-07-21_16 14 14](https://user-images.githubusercontent.com/12000593/88108035-c7ab7d80-cb6d-11ea-8028-a768497607ca.png)

**Comment by WenXin20** [comment]
This only seems to happen if all other slots in the hotbar also have an item. The glass bottle then replaces the lunar lantern in the hand

**Comment by noobanidus** [comment]
Yeah, there was no wrapper around the code to handle creative-mode, I've added that; although specifically this doesn't fix the bounding box issue, so I'll reopen.

**Comment by VulpTheHorseDog** [comment]
Everything should be fixed up as of the upcoming 0.4.4 version, let me know if anything persists.
