### ISSUE TITLE
crate texture will turn to be black in a short time after close the crate

### ISSUE THREAD

**Issue by TUsama** [MysticMods/Druidcraft#62]
### General Information

**Describe the bug:**

crate texture will turn to be black in a short time after close the crate

**To Reproduce:**
 
anytime you open crate and then just close it, you'll see the top turn black and recover soon

**Expected behavior:**

at least not turn black
***

### Environment Versions

Minecraft version: 1.15.2

mod version: 1.15-0.4.21

forge version: 31.2.31

No other mods involved

***

**Latest Log (if necessary):**
[latest.log](https://github.com/MysticMods/Druidcraft/files/4957719/latest.log)

***

### Additional Information
**Screenshots (if available):**

![Animation](https://user-images.githubusercontent.com/21279092/88132119-46a5c200-cc11-11ea-91d2-6db9e6ac5603.gif)

**Comment by VulpTheHorseDog** [comment]
So you know this is the lid opening, right?

**Comment by VulpTheHorseDog** [comment]
Barrel literally does the same thing.

**Comment by TUsama** [comment]
what?! I just know this is the animation about lid opening... ok I'll close this issue.
