### ISSUE TITLE
Woods Missing Log Tags

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/Druidcraft#65]
### General Information

**Describe the bug:**

- Woods and Stripped Logs & Woods are missing block and item log tags.

**To Reproduce:**

1. Try to craft a smoker or campfire which uses the logs tag 
2. Cannot craft with stripped darkwood logs

**Expected behavior:**

- Stripped logs to be tagged to allow to be used in recipes.

***

### Environment Versions

**Mystic Mods Versions**

- `Mystical Lib: v2.0.1`
- `Druidcraft: v0.4.21`

**Other Versions:**
- `Forge: v31.2.31`
- `Minecraft: v1.15.2`

**Comment by VulpTheHorseDog** [comment]
That's odd, it's all tagged properly for me. I'll be releasing an update soon, maybe it'll work then.
