### ISSUE TITLE
[1.15.2] multistructure crates do not act as 1 whole crate

### ISSUE THREAD

**Issue by winnetrie83** [MysticMods/Druidcraft#67]
### General Information

**Describe the bug:**
Building your multistructured crate doesn't actually make it as 1 whole crate. It still acts for some parts as individual crates.

**To Reproduce:**
1- Build a multistructured crate (for example 2 x 2)
2- Fill it let's say half to start at the top
3- Try to input more items with any other input device (hopper, pipes, etc)
4- Watch as it doesn't want to enter
5- Take 1 stack out of the crate and watch how the item that wouldn't enter, now enters.

Another example:
1- Have an empty multistructure crate
2- input something with an input device
3- See as it enters the crate but it won't be at the top left in the crate, wich is expected.

**Expected behavior:**

To function as 1 big crate and having proper support for input/output devices

***

### Environment Versions
Druidcraft-1.15-0.4.21.jar

**Mystic Mods Versions**
None

**Other Versions:**
- Forge: forge-31.2.31
- Minecraft: 1.15.2
- Modpack (if available): Valhelsia Origins - Version: 1.0.2

***

### Logging Information
not relevant

**Crash Report (if available):**
none

**Latest Log (if necessary):**
not relevant

***

### Additional Information
**Screenshots (if available):**
not relevant

**Additional context (optional):**
none

**Comment by noobanidus** [comment]
Can you confirm if this has been resolved by the recent changes to crates made in the most recent version? (Please ensure you update to the most recent version as the one before that (I believe archived, now) had an issue which meant inventories were not read properly and thus lost.)

**Comment by VulpTheHorseDog** [comment]
Closing as it has not been responded to in about a month.
