### ISSUE TITLE
Cannot disable ore generation

### ISSUE THREAD

**Issue by Akaitatsu** [MysticMods/Druidcraft#68]
### General Information

**Describe the bug:**
I would like to completely disable generation of Amber Ore and Moonstone Ore due to conflict with Silent's Gems (same issue reported there too). The lowest rarity value for both is 1 and when set to 0, it gets changed to 1. This makes for unnecessary clutter in packs with both mods.

**To Reproduce:**
1. Add Druidcraft and Silent's Gems to pack and start Minecraft
2. Edit druidcraft-server.toml so rarity for Amber and Moonstone Ore are set to 0
3. Start Minecraft and create new world
4. Druidcraft still generates Amber and Moonstone Ore and rarity is set to 1 in config file (TellMe block stats attached)

**Expected behavior:**
Setting rarity to 1 for any Druidcraft ore will prevent if from being generated in the world

***

### Environment Versions
Minecraft 1.15.2
Forge 31.2.30
Druidcraft 0.4.21
Silent's Gems 3.5.5+88

***
[block_stats_2020-08-02_15.26.28.xlsx](https://github.com/MysticMods/Druidcraft/files/5012740/block_stats_2020-08-02_15.26.28.xlsx)

**Comment by noobanidus** [comment]
Well, setting rarity to 1 should set the value to one. However, I do agree that 0 should still be a valid value and it should prevent ore from spawning.

**Comment by Akaitatsu** [comment]
Setting it to 1 _does_ reduce the amount of ore that spawns, but eliminating it should generally be an option based on other mods I have used.

Thanks for responding.

**Comment by VulpTheHorseDog** [comment]
Sorry for the wait, should be fixed in 0.4.4, releasing either tonight or tomorrow AEST.

**Comment by Akaitatsu** [comment]
Very nice. Thank you!
