### ISSUE TITLE
[1.15.2] 'mid_berry: true' flowers reset to the default state to the north when clicked on.

### ISSUE THREAD

**Issue by SuicidalSteve** [MysticMods/Druidcraft#69]
### General Information

**Describe the bug:**
When right-clicking on an elderberry block in the intermediary stage between blooming and berry it suddenly turns to the north and resets to the default state

**To Reproduce:**
1. Right click on a druidcraft:elder_fruit which has age: 3, life_stage: berry, mid_berry: true.
2. See the bug.

**Expected behavior:**
I expected the flower to not turn north and reset to the default state.

***

### Environment Versions

**Versions:**
- Druidcraft: 1.15-0.4.3
- Forge: 31.2.26
- Minecraft: 1.15.2

***

### Additional Information
**Screenshots:**
![2020-08-15_21 21 23](https://user-images.githubusercontent.com/42909981/90320207-38f90900-df3f-11ea-8f1a-8e67462f5173.png)

**Comment by VulpTheHorseDog** [comment]
You might be using some kind of mod that allows harvesting? I don't have too much control with those. I'll see if I can't get a fix going soon.

**Comment by noobanidus** [comment]
If you do have a mod that does auto-harvesting, which one is it? It's possible that it's got some sort of IMC whitelist/blacklist system that we can interface with.

**Comment by VulpTheHorseDog** [comment]
Going to close this seeing as there hasn't been an answer in about a month. Hopefully the upcoming update fixes this a little.
