### ISSUE TITLE
Crash with recent update

### ISSUE THREAD

**Issue by Vlad-Hatter** [MysticMods/Druidcraft#7]
Crash on loading
[Druidcrash.txt](https://github.com/MysticMods/Druidcraft/files/3816568/Druidcrash.txt)

**Comment by duely** [comment]
Please update your forge. 28.1.10 is, I think, actually pre-recommended build. I would suggest updating to 28.1.85, as it bypasses some of the issues with item registry/biome registry corruption.

**Comment by Vlad-Hatter** [comment]
Updated Forge.. It broke my pack all together

**Comment by VulpTheHorseDog** [comment]
You should need to update Druidcraft as well. The 0.2.1 fixes stuff like blocks not dropping and recipes being broken, which was a result of some code needing changed before release due to how obfuscation works.

Should be fixed in the newest update, but let me know if anything else crops up.
