### ISSUE TITLE
1.15.2: Bees get stuck weirdly on rope

### ISSUE THREAD

**Issue by gchpaco** [MysticMods/Druidcraft#70]
### General Information

**Describe the bug:**
I have been trying to figure out why I only ever seem to have one active beehive despite breeding several bees, and happened to look up at the ceiling and noticed that two of them appear to have climbed the Druidcraft ropes I had in the room and are chilling on the ceiling and not doing anything useful (see attached).

**To Reproduce:**
I'm honestly not sure; this was emergent observed behavior.  I think "bee flies too close to rope gets stuck" is probably most of it, though.

**Expected behavior:**
Bees to do bee things, especially going back into the home hive when they find something to pollinate, not bees getting their pathfinding stuck.

***

### Environment Versions
Minecraft 1.15.2
Java 8u242-b08

**Mystic Mods Versions**
- MysticalLib: mysticallib-1.15.2-2.0.1.jar
- Mystical World: mysticalworld-1.15.2-2.0.6.jar
- Druidcraft: Druidcraft-1.15-0.4.21.jar

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 1.15.2-31.2.36
- Minecraft: 1.15.2
- Modpack (if available): Nooby's DevCraft pack

***

### Logging Information
Omitted on account of not relevant, I don't think?

***

### Additional Information
**Screenshots:**
![Bees on the ceiling](https://user-images.githubusercontent.com/17789/90331195-42529780-df78-11ea-9ea6-f0b8ff2f8a45.png)

![More general look at the room](https://user-images.githubusercontent.com/17789/90331192-3666d580-df78-11ea-9cfc-2c9c64cb002b.png)

**Comment by VulpTheHorseDog** [comment]
Oh this is odd. I'll have to look into this.

**Comment by Vaelzan** [comment]
This might help you, a similar issue: https://github.com/mekanism/Mekanism/issues/6200

**Comment by VulpTheHorseDog** [comment]
I believe it should be better now, the fix will be released very soon on version 0.4.4.

**Comment by Vaelzan** [comment]
Appreciate it, Vulpie. Thanks. 👍
