### ISSUE TITLE
Crash from Crates having content emptied into them by simple storage network. 

### ISSUE THREAD

**Issue by Divineaspect** [MysticMods/Druidcraft#72]
### General Information

**Describe the bug:**
Crash from Crates having content emptied into them by simple storage network. 
Playing on a server, the crash is client side...

***

### Environment Versions
- Druidcraft: 1.15-0.4.31
- Forge:
- Minecraft: 1.15.2
- Simple Storage Network: 1.15.2-1.0.1
***

### Logging Information
https://pastebin.com/z8jn7x3A
https://pastebin.com/DEWM1ggM

**Comment by Divineaspect** [comment]
basically is there a reason for https://github.com/MysticMods/Druidcraft/blob/master/src/main/java/com/vulp/druidcraft/blocks/tileentities/CrateTileEntity.java#L206 ?

**Comment by noobanidus** [comment]
Hm, I'll look into it, for some reason it's considering that as part of the crate multiblock structure.

**Comment by noobanidus** [comment]
@Divineaspect Is there any chance to can provide a screenshot of how the crates were set up?

**Comment by Divineaspect** [comment]
Nope, I can't log in without immediately crashing with the bug.

**Comment by noobanidus** [comment]
Is it just the one crate? is it a multiblock? Is it connected to others?

**Comment by Divineaspect** [comment]
it's a set of four 2x2 multiblock forms connected to to the simple storage network from below, none of them are adjacent to each other.

**Comment by Divineaspect** [comment]
https://imgur.com/e3hLUxA
A single player recreation of the set up, I'm about to set up the actual filling.

**Comment by noobanidus** [comment]
Ah! 2x2x2, that actually does make a difference. I don't have the ability to look at it today, as I'm running a D&D game shortly, but I'll try to get into it tomorrow.

**Comment by Divineaspect** [comment]
we've disabled the problem atm by removing that line of code which I mention above from the clients, which while it messes up the rendering of the crates allows for actual play.

**Comment by noobanidus** [comment]
That's a suitable solution! There's an issue in the code that is for some reason off-setting weirdly and I'll need more brain power than currently is available to fix it.

**Comment by noobanidus** [comment]
I've only just had a chance to sit in and look at it now. I'm confused as to why this code is triggering on the client side. It's possible that the information stored there doesn't actually match what's on the server, but I'm struggling a little to replicate it. I'll get back to you with more details.

**Comment by noobanidus** [comment]
So with what appears to be an identical set-up I'm not experiencing the same issue:
![image](https://i.imgur.com/lLitmHJ.png)
I have put some items in the various crates.
![image](https://user-images.githubusercontent.com/8621206/92341980-cc6ac780-f102-11ea-997e-f5d657b3fc4d.png)

**Comment by Divineaspect** [comment]
fill them to the point where they move items from one block to the other, and you have to do it on a server.

**Comment by noobanidus** [comment]
Oh, these are export cables, my bad.

**Comment by noobanidus** [comment]
I don't think I understand this system enough to replicate, however the solution is simply to return an empty item handler (but an actual item handler) if the capability call is made on the client-side. The information is never synchronised to the client as far as I can tell, so it shouldn't matter in the long run.

I'll add some caching as well if my dev environment would work.

**Comment by noobanidus** [comment]
Could you try with this version? Obviously renaming .zip to .jar: [Druidcraft-1.15-0.4.32.zip](https://github.com/MysticMods/Druidcraft/files/5180896/Druidcraft-1.15-0.4.32.zip)

**Comment by Divineaspect** [comment]
Seems to resolve the crash, but now all the elderberry flowers are missing textures.

**Comment by noobanidus** [comment]
I've let Vulpie know, so that will hopefully be released soon.

**Comment by VulpTheHorseDog** [comment]
Closing now! Elderberry fix soonish I hope.
