### ISSUE TITLE
Crates Crash w/ Fairy Lights

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/Druidcraft#75]
### General Information

**Describe the bug:**

- While on my server, I tried to place a crate, but immediately got a crash with the fairy lights mod.
- No fairy lights had been placed.

**To Reproduce:**

1. Place a crate
2. Crash

**Expected Behavior:**

- No crashes
***

### Environment Versions

**Mystic Mods Versions**

- `Mystical Lib: v2.0.1`
- `Druidcraft: v0.4.4`

**Other Versions:**
- [`Fairy Lights: v3.0.11`](https://www.curseforge.com/minecraft/mc-mods/fairy-lights)
- `Forge: v31.2.45`
- `Minecraft: v1.15.2`

***

### Logging Information

**Crash Report :**

- https://gist.github.com/WenXin20/7d74e469c03236ce25dee5ce55cac302

**Comment by WenXin20** [comment]
I removed the fairy lights mod so that I could break the crate blocks in my world, but then got a crash with the [Pokecube AIO](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi) mod when I tried to break the crate...
[Crash Report](https://gist.github.com/WenXin20/73cc3983557f30f154a33c29c3fe5e7d)

**Comment by WenXin20** [comment]
Reverting to the previous version has stopped the crashes for now.
Also, the "Inventory" text is in the wrong spot when two crates are stacked on top of each other.

**Comment by noobanidus** [comment]
Either there's a mistake and it's always returning an ItemStackHandler capability, or the mods aren't checking something. I'll look into it.

**Comment by WenXin20** [comment]
Thanks. The previous version works fine with those mods, so something broke compat in the update.

**Comment by noobanidus** [comment]
Yep, this was my mistake. I believe this has been fixed in the most recent release.

**Comment by WenXin20** [comment]
Alright, thanks. I'll see if I can give it a try tomorrow.

**Comment by WenXin20** [comment]
I forgot to test it till now, this is fixed. :)
Although the "inventory" text is still in the wrong place.
