### ISSUE TITLE
Crash - Looking at Elderflower with HWYLA/WAWLA

### ISSUE THREAD

**Issue by Klaaf** [MysticMods/Druidcraft#76]
### General Information

**Describe the bug:**
The game crashes when you look at an elderflower while HWYLA is activated.

**To Reproduce:**
1. Approach elder tree
2. Activate hwyla
3. Look at elder flower

**Expected behavior:**
No crash

***

### Environment Versions

**Mystic Mods Versions**

mysticallib-1.15.2-2.0.1.jar
Druidcraft-1.15-0.4.41.jar

**Other Versions:**
Hwyla-forge-1.10.8-B72_1.15.2.jar
WAWLA-1.15.2-3.0.4.jar
Forge 31.2.45
Minecraft 1.15.2

***

### Logging Information

**Crash Report (if available):**
https://gist.github.com/Honeybadjah/def90c29d08a16f4baacc757d8940138

**Comment by noobanidus** [comment]
Yep, that's definitely an issue. Going to check sure it isn't affecting any other blocks. Otherwise it should be fixed as of 7eebb2b8454f74c5170

**Comment by noobanidus** [comment]
As far as I can tell, this should be fixed. Hopefully Vulp will be able to do a bugfix release for 1.15.

**Comment by Honeybadjah** [comment]
Yeah hopefully! Thanks
