### ISSUE TITLE
Saddle duplication glitch with crates

### ISSUE THREAD

**Issue by swordofblaze** [MysticMods/Druidcraft#78]
My modpack has a "sort container" (I'm not certain from what mod: possibly quark or JEI?) button that organizes items in a container. When a 1x2x2 upright crate has a saddle in it, and the sort container button is pressed, it adds a single extra saddle to the container, and seems to sometimes overwrite other items in the process. 

To reproduce, put a saddle in a 1x2x2 crate and press the sort container button. 

Doing so will add more saddles to the crate, and seems to overwrite other items in the process sometimes.

This glitch is in 1.15.2 with druidcraft 0.4.21 (or at least that is what multiMC says is the version)

**Comment by noobanidus** [comment]
Please update to the latest version of Druidcraft available for 1.15.2; this issue should be fixed.
