### ISSUE TITLE
[1.14.4] Latest update causes no blocks to drop.

### ISSUE THREAD

**Issue by Boomflex** [MysticMods/Druidcraft#8]
Install latest version v0.2.0 stops blocks and items from dropping.

Forge .85

**Comment by duely** [comment]
This is fixed in dev, Vulpie should be able to do a new release soon.

**Comment by oitsjustjose** [comment]
Does this also fix most registries being completely destroyed? Aside from JEI's (fake) Anvil Recipes, the game reports 0 recipes, and breaks all of my existing Silent's Tools items, causing me to crash when hovering

**Comment by duely** [comment]
Anything that is fetched from a datapack is discarded and aborted whenever there is a crash while loading *any* data pack. So yes, this would most likely fix the issue that you're having.

**Comment by VulpTheHorseDog** [comment]
Fixed as of the newest version!
