### ISSUE TITLE
JSON files to not be all in one line, to let packmakers tweak/use them easier.

### ISSUE THREAD

**Issue by CoruscareGames** [MysticMods/Druidcraft#80]
**Describe your suggestion:**
As it currently is, recipe and lang files have all of the JSON on one line, which is a pain to read and look through. I suggest line breaks be inserted for readability.

**Additional context:**
I had to look at the lang folder and the recipes folder to find a few item IDs and tweak my pack using them and datapacks in 1.16.1 so as to have this be a little different numerically from the moonstone of Silent Gems.

**Comment by noobanidus** [comment]
For future convenience, I recommend something like [JSONLint](https://jsonlint.com/) to reformat JSON properly.

**Comment by VulpTheHorseDog** [comment]
Thing is, I don't make them like that. They end up being squished when I build. Idk how to fix that.

**Comment by noobanidus** [comment]
Actually, [Vulp is right, the files in the source aren't compacted](https://github.com/MysticMods/Druidcraft/blob/master/src/main/resources/assets/druidcraft/lang/en_us.json). I'm assuming you opened the jar and fetched the json file out of it? That probably is why.

You should use the source code available in the repository instead.
