### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by lEdAtVitoko** [MysticMods/Druidcraft#81]
### General Information

I have a big problem with a Deadfish, because when I touch the Fish of Druidcraft, Minecraft crashs inmediatly.
Also the new version of Druidcraft crash Minecraft too.

**Comment by noobanidus** [comment]
Hi there!

Could you please attach a copy of the crash report or perhaps upload it to PasteBin or Gist?

**Comment by lEdAtVitoko** [comment]
Druidcraft-1.16.1-0.4.44 [crash-2020-11-04_13.26.53-server.txt](https://github.com/MysticMods/Druidcraft/files/5489073/crash-2020-11-04_13.26.53-server.txt)

**Comment by Haerar** [comment]
Druidcraft-1.16.1-0.4.46.jar can confirm the same issue I'm afraid:

[crash-2020-11-12_14.24.10-server.txt](https://github.com/MysticMods/Druidcraft/files/5531188/crash-2020-11-12_14.24.10-server.txt)

**Comment by noobanidus** [comment]
Yes, given how attribute registration changed in 1.16 this is most likely the case.

**Comment by VulpTheHorseDog** [comment]
Fixed in 1.16.3 and 1.16.4 versions!
