### ISSUE TITLE
Server Crash on Start Up

### ISSUE THREAD

**Issue by Suevi** [MysticMods/Druidcraft#82]
I don't know if this is a bug or if the mod requires 1.16.1 when I'm running 1.16.3, but I attached the crash report here if you'd like to take a look.

Crash Report: https://hastebin.com/zoporiqiba.properties

**Comment by noobanidus** [comment]
Due to significant changes in 1.16.3, mods for 1.16.1 will generally not run on it -- especially if they do anything with biomes. Vulpie is working on the 1.16.3/1.16.4 release though.
