### ISSUE TITLE
Crash Report 1.16.4

### ISSUE THREAD

**Issue by carthon** [MysticMods/Druidcraft#86]
### General Information

**Describe the bug:**
Game crash on load

***
**Other Versions:**
- Forge: 35.1.8
- Minecraft: 1.16.4

**Crash Report (if available):**

[crash-2020-12-27_08.40.24-fml.txt](https://github.com/MysticMods/Druidcraft/files/5744208/crash-2020-12-27_08.40.24-fml.txt)

**Latest Log (if necessary):**

[latest.log](https://github.com/MysticMods/Druidcraft/files/5744209/latest.log)

***

**Comment by Klaaf** [comment]
Mod version is for 1.16.1

**Comment by noobanidus** [comment]
There is no 1.16.3 or 1.16.4 release yet.
